add livepeer staking adaptor
zeriontech/defi-sdk pull request #135
Opened 2021-01-23 00:18 UTC by adamsoffer

This PR adds a staking adapter for the Livepeer protocol. Note: the [metadata](https://github.com/zeriontech/defi-sdk/compare/master...adamsoffer:livepeer-adaptor?expand=1#diff-7d6910f4d9b0ea604c8a7575be91ff6fce9083b589736da559e0b11ecaa712c9R1186) references the livepeer logo (`protocol-icons.s3.amazonaws.com/livepeer.png`) which doesn't yet exist in your s3 bucket so someone will have to upload it (attached below).

Thanks! Let me know if this needs any changes.

![livepeer](https://user-images.githubusercontent.com/555740/105561475-cc9be600-5ce4-11eb-84e4-3c69c37b3cf7.png)

2021-01-25 19:44 UTC, cr-igor requested changes

2021-01-25 19:44 UTC, cr-igor commented on contracts/adapters/livepeer/LivepeerStakingAdaptor.sol
> +        return BondingManager(BONDING_MANAGER).pendingStake(account, currentRound);
if the only one token may be staked, please add 
```
if (token == TOKEN) {
    *your code*
} else {
    return 0
}
```

2021-01-25 19:44 UTC, cr-igor commented on contracts/adapters/livepeer/LivepeerStakingAdaptor.sol
> +        return BondingManager(BONDING_MANAGER).pendingStake(account, currentRound);
token here is the first param of the function

2021-01-25 19:46 UTC, cr-igor requested changes

2021-01-25 19:46 UTC, cr-igor commented on contracts/adapters/livepeer/LivepeerStakingAdaptor.sol
> +contract LivepeerAdapter is ProtocolAdapter {
```suggestion
contract LivepeerStakingAdapter is ProtocolAdapter {
```

2021-01-25 19:46 UTC, cr-igor commented on migrations_scripts/1_deploy_registry_and_add_adapters.js
> +const LivepeerStakingAdaptor = artifacts.require('LivepeerStakingAdaptor');
```suggestion
const LivepeerStakingAdapter = artifacts.require('LivepeerStakingAdapter');
```

2021-01-25 19:46 UTC, cr-igor commented on migrations_scripts/1_deploy_registry_and_add_adapters.js
> +  await deployer.deploy(LivepeerStakingAdaptor, { from: accounts[0] });
```suggestion
  await deployer.deploy(LivepeerStakingAdapter, { from: accounts[0] });
```

2021-01-25 19:46 UTC, cr-igor commented on contracts/adapters/livepeer/LivepeerStakingAdaptor.sol
> +        return BondingManager(BONDING_MANAGER).pendingStake(account, currentRound);
and LPT as internal constant variable

2021-01-25 19:49 UTC, cr-igor commented
Everything is cool except for things I've commented) we've deprecated logos' urls, so it's OK it's not loaded to s3, if it's important for you we can upload it)

2021-01-25 20:32 UTC, adamsoffer commented
Thanks for the review @cr-igor - I just pushed up the requested fixes/changes. 

> we've deprecated logos' urls, so it's OK it's not loaded to s3, if it's important for you we can upload it)
The logo I attached is an improvement on the one currently being used in Zerion which gets appears off/cropped, so if you can upload the one attached to be used instead that would be great!

2021-01-26 09:33 UTC, cr-igor approved these changes

2021-01-26 09:33 UTC, merged

2021-01-26 12:54 UTC, cr-igor commented
@adamsoffer could you please also provide an example address with the amount this adapter should return (it may change, but approx value will be enough)? 

btw, we've updated the token icon, but the old one may be cached for some time)

2021-01-26 15:53 UTC, adamsoffer commented
@cr-igor sure. Here's an example address that has 195,413 LPT staked: `0x4f4758f7167b18e1f5b3c1a7575e3eb584894dbc`

Note: this number will increase when it receives its inflationary reward at the end of the current round in a few hours.