Add amun liquidity adapters
zeriontech/defi-sdk pull request #155
Opened 2021-06-07 11:51 UTC by loki-sama

Adds Amun liquidity simple and interactive adapters
Adds tests for adapters

2021-06-07 15:20 UTC, sobolev-igor commented on contracts/interactiveAdapters/Amun/AmunLiquidityInteractiveAdapter.sol
> +        ERC20(token).safeApprove(liquidityToken, amount, "LBIA");
please use `safeApproveMax` here

2021-06-07 15:21 UTC, sobolev-igor commented
Here everything seems to be correct, except for `safeApproveMax` function call

2021-06-08 07:55 UTC, loki-sama commented on contracts/interactiveAdapters/Amun/AmunLiquidityInteractiveAdapter.sol
> +        ERC20(token).safeApprove(liquidityToken, amount, "LBIA");
I updated to safeApproveMax

2021-06-08 07:57 UTC, loki-sama commented
There is only one liquidity token: '0x9D895763488a9f60D1882296cBe23399f974E10d'

2021-06-09 10:53 UTC, sobolev-igor requested changes

2021-06-09 10:53 UTC, sobolev-igor commented on contracts/interactiveAdapters/Amun/AmunLiquidityInteractiveAdapter.sol
> +    uint8 referralCode = 101;
```suggestion
    uint8 internal constant REFERRAL_CODE = 101;
```

2021-06-09 10:53 UTC, sobolev-igor commented on contracts/interactiveAdapters/Amun/AmunLiquidityInteractiveAdapter.sol
> +        try IVault(liquidityToken).deposit(amount, referralCode)  {} catch Error(
```suggestion
        try IVault(liquidityToken).deposit(amount, REFERRAL_CODE)  {} catch Error(
```

2021-06-09 10:53 UTC, sobolev-igor commented on contracts/interactiveAdapters/Amun/AmunLiquidityInteractiveAdapter.sol
> +        try IVault(token).withdraw(amount, referralCode)  {} catch Error(string memory reason) {
```suggestion
        try IVault(token).withdraw(amount, REFERRAL_CODE)  {} catch Error(string memory reason) {
```

2021-06-09 11:56 UTC, loki-sama commented on contracts/interactiveAdapters/Amun/AmunLiquidityInteractiveAdapter.sol
> +    uint8 referralCode = 101;
👍

2021-06-09 13:43 UTC, sobolev-igor requested changes

2021-06-09 13:43 UTC, sobolev-igor commented on contracts/interactiveAdapters/Amun/AmunLiquidityInteractiveAdapter.sol
> +    uint8 internal constant REFERRAL_CODE = 101;
```suggestion
    uint16 internal constant REFERRAL_CODE = 101;
```

2021-06-10 09:01 UTC, loki-sama commented on contracts/interactiveAdapters/Amun/AmunLiquidityInteractiveAdapter.sol
> +    uint8 internal constant REFERRAL_CODE = 101;
👍  Thanks

2021-06-22 09:40 UTC, merged