Amun lending adapters
zeriontech/defi-sdk pull request #156
Opened 2021-06-07 12:00 UTC by loki-sama

Adds Amun lending simple and interactive adapters
Adds tests for adapters

2021-06-07 15:17 UTC, sobolev-igor commented
For our system to work properly, components returned by token adapter should be the same as returned tokens in `withdraw()` function of interactive adapter. So, you need to use function returning yTokens in `withdraw()` or calculate rate to underlying stablecoin in token adapter.

2021-06-07 15:23 UTC, sobolev-igor commented on contracts/interactiveAdapters/Amun/AmunLendingtInteractiveAdapter.sol
> +        ERC20(tokenAmounts[0].token).safeApprove(lendingToken, amount, "LBIA[1]");
please use `safeApproveMax` here

2021-06-08 07:58 UTC, loki-sama commented
There is only one lending token: 0x78f9c12e15ec36C2AB1bE0b2e5f79B71A9ECdFC8

2021-06-09 10:50 UTC, sobolev-igor requested changes

2021-06-09 10:50 UTC, sobolev-igor commented on contracts/interactiveAdapters/Amun/AmunLendingtInteractiveAdapter.sol
> +    uint8 referralCode = 101;
```suggestion
    uint8 internal constant REFERRAL_CODE = 101;
```

2021-06-09 10:50 UTC, sobolev-igor commented on contracts/interactiveAdapters/Amun/AmunLendingtInteractiveAdapter.sol
> +                referralCode
```suggestion
                REFERRAL_CODE
```

2021-06-09 10:50 UTC, sobolev-igor commented on contracts/interactiveAdapters/Amun/AmunLendingtInteractiveAdapter.sol
> +                referralCode
```suggestion
                REFERRAL_CODE
```

2021-06-09 10:50 UTC, sobolev-igor commented on contracts/interactiveAdapters/Amun/AmunLendingtInteractiveAdapter.sol
> +     * @return tokensToBeWithdrawn Array with one element - rebalancing set address.
```suggestion
     * @return tokensToBeWithdrawn Array with one element - AmunBasket address.
```

2021-06-09 10:50 UTC, sobolev-igor commented on contracts/interactiveAdapters/Amun/AmunLendingtInteractiveAdapter.sol
> +     * @notice Withdraws tokens from the TokenSet.
```suggestion
     * @notice Withdraws tokens from the AmunBasket.
```

2021-06-22 09:56 UTC, merged